include:
  - ubuntu-client.pkgs.freshplayerplugin
  - ubuntu-client.pkgs.google-chrome-stable
  - ubuntu-client.pkgs.htop
  - ubuntu-client.pkgs.keepass
  - ubuntu-client.pkgs.java
  - ubuntu-client.pkgs.nmap
  - ubuntu-client.pkgs.owncloud-client
  - ubuntu-client.pkgs.pac
  - ubuntu-client.pkgs.python-gpgme
  - ubuntu-client.pkgs.python-software-properties
  - ubuntu-client.pkgs.traceroute
  - ubuntu-client.pkgs.ufw
  - ubuntu-client.pkgs.vpnc
  - ubuntu-client.pkgs.wireshark
